name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-landing:
    name: Build Landing Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: landing-page-files
          path: ./dist

  build-org:
    name: Build Organization Site
    if: github.repository == 'nus-cs2103de-AY2425S1/nus-cs2103de-AY2425S1.github.io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production
          DEPLOY_TARGET: org

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: org-site-files
          path: ./dist

  deploy-landing:
    name: Deploy Landing Page
    needs: build-landing
    if: github.repository == 'nus-cs2103de-AY2425S1/landing-page'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: landing-page-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  deploy-org:
    name: Deploy Organization Site
    needs: build-org
    if: github.repository == 'nus-cs2103de-AY2425S1/nus-cs2103de-AY2425S1.github.io'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: org-site-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist 